### ISSUE TITLE
Link Not Working?

### ISSUE THREAD

**Issue by Argonity** [learn-co-curriculum/ruby-cli-applications-readme#10]
Within this readme, there's the BIN section with a link that doesn't seem to be working. Name of the link is 'running CLI applications'.

BIN/
Within the bin/ directory we generally put code that relates to running our actual program. Our executable files that we put in bin are described below, [running CLI applications](url).

**Comment by AnnJohn** [comment]
hi @Argonity the link just takes you to that section further down in this repo. thanks!
