### ISSUE TITLE
Small error in CLI Applications In Ruby readme example

### ISSUE THREAD

**Issue by YogiBogie** [learn-co-curriculum/ruby-cli-applications-readme#13]
Hello,

In the last example where you give an example of how the tic tac toe game might run you give the following example:

**Please select a square by entering 1-9, 1 for the top left and 9 for the bottom right:
5↵
 
  O |    |   
-----------
     | X |   
-----------
     |    |      

An 'O' appears in square 1 without any user input, should that be there or perhaps was the 'O' placed there by mistake?

**Comment by gj** [comment]
Thanks for pointing this out @YogiBogie !
