### ISSUE TITLE
File Permissions

### ISSUE THREAD

**Issue by thistonyb** [learn-co-curriculum/ruby-cli-applications-readme#16]
So this lesson talks about file permissions and under that section it talks about chmod and sudo. Both are not related to windows and one for sure is specifically a linux command. Without context to this in the lesson you are going to confuse a lot of people! I find these bits and pieces throughout the lessons and am tired of looking them up or being tripped up because they do not pertain to windows users. Please make this lesson clearer. At the very least say this will apply to Mac OS or Linux. If you want everyone in the class to be using BASH, tell them to download the windows subsystem for linux.....

**Comment by drakeltheryuujin** [comment]
Hi @thistonyb,

Thank you for your feedback! Our default supported platforms for this curriculum are Ubuntu in a VM, Linux, qnd OSX. Unfortunately, we don't have much support for windows native. If you can let us know which program you are in, we'll take this information into consideration to make this more clear in the future. 

Thanks for contributing! 💙

**Comment by drakeltheryuujin** [comment]
@thistonyb 

We have this guide for setting up Windows Subsystem Linux for Windows 10 users if this would be helpful for you moving forward: https://github.com/micahshute/wsl-setup
