### ISSUE TITLE
Teaching Flow

### ISSUE THREAD

**Issue by faiyamTestFS32** [learn-co-curriculum/ruby-cli-applications-readme#6]
This "Command Line Applications" section begins with a ditty on how CLI applications made the modern software-driven world possible, how important they are, and thus why you should learn about them. 

It then goes into a bunch of stuff that doesn't seem *quite* directly relevant: folder structures, binaries/executables, etc. It *is* relevant because those macro concepts are necessary to write good CLI applications. But we'd do good to tell the student what to expect. 

Perhaps a section at the end of the "Intro to Command Line Applications" section could say:

> # Conclusion

> Now you know why Command Line applications are such a big deal. In the next few sections, we'll learn a few things about programming best practices that will help you write great CLI applications.

**Comment by AnnJohn** [comment]
Added a sentence at the end of the previous Intro to CLI application Closing.
